# Permalinks
#
permalink:           pretty

# Setup
title:               Eviatar Bach
tagline:             
#url:                 "http://www.phas.ubc.ca/~eviatarb"
#baseurl:             "http://www.phas.ubc.ca/~eviatarb"
markdown:            maruku
kramdown:
      parse_block_html: true
      smart_quotes: ["apos", "apos", "quot", "quot"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Eviatar Bach
  url:               
  email:             eviatarbach@gmail.com

# Custom vars
version:             
github:
  repo:              https://github.com/eviatarbach/eviatarbach.github.io
