# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Eviatar Bach
tagline:             
url:                 
paginate:            1
baseurl:             ""
markdown:            kramdown
kramdown:
      parse_block_html: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Eviatar Bach
  url:               
  email:             eviatarbach@gmail.com

# Custom vars
version:             
github:
  repo:              https://github.com/eviatarbach/eviatarbach.github.io
